### ISSUE TITLE
Bot won't respond to Commands

### ISSUE THREAD

**Issue by rfreedman5280** [cameroncros/OctoPrint-DiscordRemote#212] opened 2021-12-16 16:38 UTC
Hi there,
I've had a ton of success with this plugin for about a year now, but I'm having some issues with the bot now. It sends regularly scheduled status messages but won't recognize the /status or /help commands. I tried changing the command symbol to $ with no change. I also reset the bot token in discord and updated it, with no change. Any tips? I'm running a print right now so there's a chance restarting when I'm done will fix this.
Thanks!

**Comment by cameroncros** [comment] 2021-12-18 02:07
Yup, I have noticed this as well :( I will look into it today

**Comment by rfreedman5280** [comment] 2021-12-18 02:23
Thanks so much! I appreciate your help!

**Comment by cameroncros** [comment] 2021-12-18 07:25
I have pushed some fixes that should hopefully make the code a lot more reliable. I noticed that when you change the settings, the bot goes offline, and doesnt come back. It will now correctly come back. Hopefully that was the cause of both of our issues, and I will close this ticket. If the issues persist after updating, please re-open the ticket

**Closed by cameroncros** 2021-12-18 07:25 UTC
