### ISSUE TITLE
Bot not responding to commands

### ISSUE THREAD

**Issue by bertoo87** [cameroncros/OctoPrint-DiscordRemote#82] opened 2019-05-22 10:49 UTC
Hi guys.

since the last update i had to fully reconfigure DR.
the bot is in the correct channel and posting every 5% of the print.
but when i send a status request or any other command like /abort it doesnt react at all. the bot has every text message permission. and for some odd reason the bot is shown as offline to the right.

any suggestions?

**Comment by cameroncros** [comment] 2019-05-22 11:12
This is a duplicate of #81

**Closed by cameroncros** 2019-05-22 11:12 UTC
