### ISSUE TITLE
Presence broken

### ISSUE THREAD

**Issue by DigiVore-Programing** [cameroncros/OctoPrint-DiscordRemote#196] opened 2021-08-06 02:10 UTC
**Describe the bug**
Not showing anything in the Discord bot's presence data. 

*Logs*
[plugin_discordremote.log](https://github.com/cameroncros/OctoPrint-DiscordRemote/files/6942553/plugin_discordremote.log)

**To Reproduce**
1. Install plugin
2. Setup plugin.
3. TURN OFF PRESANCE (inverted btw)

**Expected behavior**
Working presence data

**Screenshots**
![image](https://user-images.githubusercontent.com/38924918/128445181-b2f5c265-8121-402e-9459-1c92b654bba5.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Brave

**Smartphone (please complete the following information):**
 - Device: Galaxy S10+
 - OS: Android 11
 - Browser: Chrome

**Additional context**
Plugin needs to be fixed asap, I will pay for the fix tbh.

**Comment by cameroncros** [comment] 2021-08-14 10:38
This is a duplicate of #194. If you really need this fixed and are willing to pay for it, I can probably look into it, but otherwise I am not likely to have the time.

**Closed** 2021-10-17 02:12 UTC
